# Generated by Django 2.1.4 on 2020-03-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='20字以内', max_length=20, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='50字以内', max_length=50, verbose_name='文章标题')),
                ('cover', models.URLField(verbose_name='文章封面')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('digg_count', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '文章详情',
                'verbose_name_plural': '文章详情',
                'db_table': 'article_detail',
            },
        ),
    ]
