# Generated by Django 2.1.4 on 2020-03-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='user.Users'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='category1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category1', to='article.ArticleCategory'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='category2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category2', to='article.ArticleCategory'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article.ArticleCategory', verbose_name='父级分类'),
        ),
    ]
