# Generated by Django 2.1.4 on 2020-03-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200306_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledetail',
            options={'ordering': ['-create_time'], 'verbose_name': '文章详情', 'verbose_name_plural': '文章详情'},
        ),
    ]
