# Generated by Django 2.1.4 on 2020-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200308_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='des',
            field=models.TextField(default=123, verbose_name='文章简介'),
            preserve_default=False,
        ),
    ]
