# Generated by Django 2.1.4 on 2020-03-09 08:19

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articledetail_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
    ]
