# Generated by Django 2.1.4 on 2020-03-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200309_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLabel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='文章标签')),
                ('article', models.ManyToManyField(related_name='labels', to='article.ArticleDetail')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
                'db_table': 'labels',
            },
        ),
    ]
