# Generated by Django 2.1.4 on 2020-03-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200309_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articledetail',
            old_name='article',
            new_name='labels',
        ),
    ]
