# Generated by Django 2.1.4 on 2020-03-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200310_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
