# Generated by Django 2.1.4 on 2020-03-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0003_auto_20200308_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleDetail')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'carousel',
            },
        ),
    ]
